version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install
      - cd ../frontend
      - npm install

  build:
    commands:
      - npm run build
      - cd ..

artifacts:
  files:
    - frontend/build/**/*  # Frontend build artifacts
    - backend/**/*          # Backend files
    - appspec.yml
    - scripts/**/*          # Deployment scripts
