version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install
      - cd ../backend
      - npm install

  build:
    commands:
      - cd frontend
      - npm run build
      - cd ../backend
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  base-directory: backend
  discard-paths: yes
